export default {
  terms: {
    download: 'Download',
    completion_time: 'Completion time',
    status: 'Status',
    total: 'Total',
    column: 'Column',
    sticky_column: 'Sticky column',
    rows_per_page: 'Rows per page',
    options: 'Options',
    history: 'History',
    apply_filters: 'Apply filters',
    create_report: 'Create report',
    run_report: 'Run report',
    report: 'Report',
    search_report: 'Search report',
    report_type: '@:advertising.terms.report type',
    report_name: '@:advertising.terms.report name',
    report_period: '@:advertising.terms.report period',
    field_options: (ctx) => `${ctx.named('field')} ${ctx.linked('general.terms.options').toLowerCase()}`,
  },
  terminology: {
    portfolio: 'Portfolio',
    campaign: 'Campaign',
    ad_group: 'Ad group',
    target: 'Target',
    targets: 'Targets',
    acos: 'ACoS',
    tacos: 'TACoS',
    roas: 'RoAS',
    impressions: 'Impressions',
    clicks: 'Clicks',
    orders: 'Orders',
    cpc: 'CPC',
    cvr: 'CVR',
    ctr: 'CTR',
    aov: 'AoV',
    automation_status: 'Automation status',
    targeted_acos: 'Targeted ACoS',
    targeted_tacos: 'Targeted TACoS',
    amazon_bidding_strategy: 'Amazon Bidding Strategy',
    budget: 'Budget',
    bid: 'Bid',
    bid_adjustment: 'Bid adjustment',
    bidding: 'Bidding',
    strategy: 'Strategy',
    spend: 'Spend',
    sales: 'Sales',
    product: 'Product',
    product_name: '@:advertising.terminology.product name',
    asin: 'ASIN',
    asins: 'Asins',
    placements: 'Placements',
    target_type: '@:advertising.terminology.target type',
    campaign_type: '@:advertising.terminology.campaign type',
    campaign_bidding_strategy: '@:advertising.terminology.campaign bidding strategy',
    campaign_status: '@:advertising.terminology.campaign status',
    campaign_automation_status: '@:advertising.terminology.campaign automation status',
    inventory_status: 'Inventory status',
    expand_asins: 'Expand asins',
    expand_targets: 'Expand targets',
    expand_placements: 'Expand placements',
  },
  components: {
    dashboard: {
      sync_from: 'Sync from',
      syncing_from: 'Syncing from',
      choose_right_acc: "Selected Amazon advertising account does not have access for selected Eva store, can't connect advertising account. Please choose the right store and try again.",
    },
    connect_store: {
      you_have_not_adv_acc: "YOU HAVEN'T ADDED ANY AMAZON ADVERTISING ACCOUNT YET.",
      connect_adv_acc: "Please connect your Amazon Advertising Account to receive Eva Advertising Analytics data.",
      connect_ad_acc: 'Connect Ad Account',
    },
    sync_store: {
      syncing_with_amazon_ads_acc: 'Syncing with Amazon Ads Account',
      we_are_now_syncing_your_amz_acc: "We're now syncing with your Amazon Advertising Account.",
      it_may_take_a_while: "It may take a while, and we'll let you know when your account is ready.",
    },
    headers: {
      amazon_bidding_strategy: (ctx) => `Amazon<br><div class='flex'><span>${ctx.linked('advertising.terminology.bidding').toLowerCase()}</span>&nbsp;<span>${ctx.linked('advertising.terminology.strategy').toLowerCase()}</span></div>`,
    },
    rule_parameters: {
      system_rules_enabled: 'System rules enabled',
      automation_target_type: 'Automation target type'
    }
  }
}